version: '3.3'
services:
  client:
    container_name: nginx-client-app
    restart: always
    build: client-app
    ports:
      - '8080:80'
    environment:
      - API_HOST=192.168.50.103 # hostname -I
      - API_PORT=3001
    networks:
      - dockernet
networks:
  dockernet:

      


