# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Install deps with Yarn
    - name: Install dependencies
      run: yarn
      working-directory: ./user-service
    
    # Run linter checks
    - name: Run TS lint
      run: yarn lint
      working-directory: ./user-service

    # Run tests
    - name: Run tests
      run: yarn test
      working-directory: ./user-service


  deploy-user-service:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest
    # only run if build job complte successfully 
    needs: [tests]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      run: |
        docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
  
    - name: Build the Docker image
      run: docker build ./user-service --file ./user-service/Dockerfile --tag iivashchuk/jsprocamp-user-service:latest
      
    - name: Docker Push
      run: docker push iivashchuk/jsprocamp-user-service

  deploy-chat-service:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest
    # only run if build job complte successfully 
    needs: [tests]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      run: |
        docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
  
    - name: Build the Docker image
      run: docker build ./chat-service --file ./chat-service/Dockerfile --tag iivashchuk/jsprocamp-chat-service:latest
      
    - name: Docker Push
      run: docker push iivashchuk/jsprocamp-chat-service

  deploy-chat-client:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest
    # only run if build job complte successfully 
    needs: [tests]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      run: |
        docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
  
    - name: Build the Docker image
      run: docker build ./client-app --file ./client-app/Dockerfile --tag iivashchuk/jsprocamp-client-app:latest
      
    - name: Docker Push
      run: docker push iivashchuk/jsprocamp-client-app

  deploy-auth-middleware:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest
    # only run if build job complte successfully 
    needs: [tests]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      run: |
        docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
  
    - name: Build the Docker image
      run: docker build ./facebook-oauth-middleware --file ./facebook-oauth-middleware/Dockerfile --tag iivashchuk/jsprocamp-facebook-oauth-middleware:latest
      
    - name: Docker Push
      run: docker push iivashchuk/jsprocamp-facebook-oauth-middleware